name: hallo_doctor_client
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  firebase_messaging: ^14.2.1
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  cloud_functions: ^4.0.7
  firebase_database: ^10.0.9
  flutter_exit_app: ^1.0.4
  google_sign_in: ^5.3.3
  flutter_signin_button: ^2.0.0
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.0.9
  google_fonts: ^3.0.1
  carousel_slider: ^4.1.1
  flutter_rating_bar: ^4.0.1
  string_validator: ^0.3.0
  flutter_chat_types: ^3.6.0
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  path: ^1.8.0
  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.2.0
  date_picker_timeline: ^1.2.3
  flutter_stripe: ^3.1.0
  flutter_svg: ^1.0.3
  lottie: ^1.3.0
  http: ^0.13.4
  rounded_loading_button: ^2.1.0
  flutter_form_builder: 7.0.0
  form_builder_validators: ^8.1.1
  package_info_plus: ^1.4.2
  open_file: ^3.2.1
  file_picker: ^4.6.1
  uuid: ^3.0.6
  mime: ^1.0.2
  flutter_chat_ui: ^1.6.6

  flutter_local_notifications: ^9.7.0
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  jiffy: ^5.0.0
  agora_rtc_engine: ^5.2.0
  permission_handler: ^9.2.0
  custom_flutter_callkit_incoming: ^1.2.3
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  image_cropper: ^2.0.3
  url_launcher: ^6.1.5
  splashscreen:
    git:
      url: https://github.com/DPLYR-dev/SplashScreenFlutterPackage.git
      ref: master
  flutter_facebook_auth: ^4.4.1+1
  intl_phone_field: ^3.1.0
  go_sell_sdk_flutter: ^2.2.0
  auto_reload: ^1.1.0
  rflutter_alert: ^2.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  change_app_package_name: ^1.1.0
  build_runner: ^2.1.11
  flutter_firebase_chat_core: ^1.6.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/ic_launcher.png"

flutter_native_splash:
  color: "#1b4170"
  image: "assets/icons/splash.gif"
